# Generated by Django 5.0.6 on 2026-04-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="correct_items",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="answer",
            name="total_items",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
