# Generated by Django 5.0.6 on 2026-05-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0002_answer_correct_items_answer_total_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="is_draft",
            field=models.BooleanField(
                default=False,
                help_text="Taslak olarak kaydedildiyse (Daha sonra devam et) True",
            ),
        ),
    ]
