# Generated by Django 5.0.6 on 2026-05-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0003_submission_is_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="ai_feedback",
            field=models.TextField(
                blank=True,
                help_text='Bu soruya özel "Cevabın doğru ama şu detayı atlamışsın" notu',
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="ai_score",
            field=models.FloatField(
                blank=True,
                help_text="Bu soruya özel AI Semantik Benzerlik oranı (örn: 0.85)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="ai_feedback",
            field=models.TextField(
                blank=True,
                help_text="Yapay zekanın öğrenciye özel genel geri bildirimi",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="ai_score",
            field=models.FloatField(
                blank=True,
                help_text="Yapay zekanın performansa verdiği genel güven/başarı skoru",
                null=True,
            ),
        ),
    ]
