# Generated by Django 5.0.6 on 2026-04-27 20:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worksheets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workbook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='workbook_covers/')),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workbooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dijital Defter',
                'verbose_name_plural': 'Dijital Defterler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkbookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('workbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='workbooks.workbook')),
                ('worksheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worksheets.worksheet')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('workbook', 'worksheet')},
            },
        ),
    ]
