# Generated by Django 5.0.6 on 2026-04-27 20:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('fill_blank', 'Textfield'), ('multiple_choice', 'Single Choice'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Select'), ('drag_drop', 'Drag & Drop'), ('matching', 'Join'), ('speech', 'Speak'), ('open_answer', 'Open Answer'), ('simple_text', 'Simple Text'), ('play_mp3', 'Play MP3')], max_length=20)),
                ('order', models.PositiveIntegerField(default=1)),
                ('pos_x', models.FloatField(default=10)),
                ('pos_y', models.FloatField(default=10)),
                ('width', models.FloatField(default=15)),
                ('height', models.FloatField(default=5)),
                ('label', models.CharField(blank=True, max_length=500)),
                ('correct_answer', models.TextField(blank=True)),
                ('font_size', models.PositiveIntegerField(default=14)),
                ('bg_color', models.CharField(default='#ffffff', max_length=7)),
                ('border_color', models.CharField(default='#cccccc', max_length=7)),
            ],
            options={
                'verbose_name': 'Soru',
                'verbose_name_plural': 'Sorular',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Ders',
                'verbose_name_plural': 'Dersler',
            },
        ),
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_text', models.CharField(max_length=255)),
                ('right_text', models.CharField(max_length=255)),
                ('left_image', models.ImageField(blank=True, null=True, upload_to='matching/')),
                ('right_image', models.ImageField(blank=True, null=True, upload_to='matching/')),
                ('order', models.PositiveIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_pairs', to='worksheets.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DragDropTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.CharField(max_length=50)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('pos_x', models.FloatField(default=0)),
                ('pos_y', models.FloatField(default=0)),
                ('width', models.FloatField(default=10)),
                ('height', models.FloatField(default=5)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_targets', to='worksheets.question')),
            ],
        ),
        migrations.CreateModel(
            name='DragDropItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='drag_items/')),
                ('correct_target_id', models.CharField(blank=True, help_text='Hangi hedef kutucuğa ait', max_length=50)),
                ('order', models.PositiveIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drag_items', to='worksheets.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChoiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='worksheets.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(blank=True, choices=[('anaokulu', 'Anaokulu'), ('ilkokul', 'İlkokul'), ('ortaokul', 'Ortaokul'), ('lise', 'Lise'), ('universite', 'Üniversite'), ('yetiskin', 'Yetişkin')], max_length=20)),
                ('language', models.CharField(choices=[('tr', 'Türkçe'), ('en', 'İngilizce'), ('de', 'Almanca'), ('fr', 'Fransızca'), ('es', 'İspanyolca'), ('ar', 'Arapça')], default='tr', max_length=5)),
                ('is_public', models.BooleanField(default=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('tags', models.CharField(blank=True, help_text='Virgülle ayrılmış etiketler', max_length=500)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worksheets', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worksheets.subject')),
            ],
            options={
                'verbose_name': 'Çalışma Kağıdı',
                'verbose_name_plural': 'Çalışma Kağıtları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorksheetPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
                ('background_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('page_width', models.PositiveIntegerField(default=794)),
                ('page_height', models.PositiveIntegerField(default=1123)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('audio_url', models.URLField(blank=True)),
                ('text_to_speech_text', models.TextField(blank=True)),
                ('text_to_speech_lang', models.CharField(default='tr', max_length=5)),
                ('worksheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='worksheets.worksheet')),
            ],
            options={
                'verbose_name': 'Sayfa',
                'verbose_name_plural': 'Sayfalar',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='worksheets.worksheetpage'),
        ),
        migrations.CreateModel(
            name='MediaEmbed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embed_type', models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo')], max_length=10)),
                ('video_url', models.URLField()),
                ('video_id', models.CharField(blank=True, max_length=50)),
                ('pos_x', models.FloatField(default=0)),
                ('pos_y', models.FloatField(default=0)),
                ('width', models.FloatField(default=40)),
                ('height', models.FloatField(default=25)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeds', to='worksheets.worksheetpage')),
            ],
        ),
    ]
