# Generated by Django 5.0.6 on 2026-04-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worksheets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("fill_blank", "Textfield"),
                    ("multiple_choice", "Single Choice"),
                    ("checkboxes", "Checkboxes"),
                    ("dropdown", "Select"),
                    ("drag_drop", "Drag & Drop (eski)"),
                    ("drag_word", "Drag Word"),
                    ("drop_zone", "Drop Zone"),
                    ("matching", "Join"),
                    ("speech", "Speak"),
                    ("open_answer", "Open Answer"),
                    ("simple_text", "Simple Text"),
                    ("play_mp3", "Play MP3"),
                ],
                max_length=20,
            ),
        ),
    ]
