# Generated by Django 5.0.6 on 2026-04-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worksheets", "0002_add_drag_word_drop_zone"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="points",
            field=models.PositiveIntegerField(
                default=1, help_text="Bu soru kaç puan değerinde?"
            ),
        ),
    ]
