# Generated by Django 5.0.6 on 2026-05-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worksheets", "0003_question_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksheet",
            name="grading_system",
            field=models.CharField(
                choices=[
                    ("100", "100'lük Sistem (0–100 puan)"),
                    ("10", "10'luk Sistem (0–10 puan)"),
                ],
                default="100",
                help_text="Öğrenciye gösterilecek puan sistemi",
                max_length=3,
                verbose_name="Puanlama Sistemi",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("fill_blank", "Textfield"),
                    ("multiple_choice", "Single Choice"),
                    ("checkboxes", "Checkboxes"),
                    ("dropdown", "Select"),
                    ("drag_drop", "Drag & Drop (eski)"),
                    ("drag_word", "Drag Word"),
                    ("drop_zone", "Drop Zone"),
                    ("matching", "Join"),
                    ("speech", "Speak"),
                    ("open_answer", "Open Answer"),
                    ("simple_text", "Simple Text"),
                    ("play_mp3", "Play MP3"),
                    ("word_choice", "Kelime Seçimi (word1 / word2)"),
                ],
                max_length=20,
            ),
        ),
    ]
