# Generated by Django 5.0.6 on 2026-05-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worksheets", "0004_add_grading_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="learning_objective",
            field=models.CharField(
                blank=True,
                help_text='Yapay Zeka öneri motoru için öğrenme kazanımı/etiketi (Örn: "Kesirlerde Toplama", "Geçmiş Zaman Kişi Ekleri")',
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="worksheet",
            name="language",
            field=models.CharField(
                choices=[
                    ("tr", "Türkçe"),
                    ("en", "İngilizce"),
                    ("de", "Almanca"),
                    ("fr", "Fransızca"),
                    ("es", "İspanyolca"),
                    ("ar", "Arapça"),
                    ("pt", "Portekizce"),
                    ("ru", "Rusça"),
                    ("zh-hans", "Çince"),
                    ("it", "İtalyanca"),
                    ("ko", "Korece"),
                ],
                default="tr",
                max_length=15,
            ),
        ),
    ]
