# Generated by Django 5.0.6 on 2026-04-27 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('allow_multiple_attempts', models.BooleanField(default=False)),
                ('show_answers', models.BooleanField(default=True, help_text='Bitişte doğru cevapları göster')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classrooms', models.ManyToManyField(blank=True, related_name='assignments', to='accounts.classroom')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ödev',
                'verbose_name_plural': 'Ödevler',
                'ordering': ['-created_at'],
            },
        ),
    ]
