# Generated by Django 5.0.6 on 2026-04-27 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('workbooks', '0001_initial'),
        ('worksheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='workbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='workbooks.workbook'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='worksheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='worksheets.worksheet'),
        ),
    ]
